// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package etcdclientpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EtcdclientClient is the client API for Etcdclient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EtcdclientClient interface {
	Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	AddBlog(ctx context.Context, in *AddBlogRequest, opts ...grpc.CallOption) (*AddBlogResponse, error)
	ListBlog(ctx context.Context, in *ListBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error)
	GetBlog(ctx context.Context, in *GetBlogRequest, opts ...grpc.CallOption) (*GetBlogResponse, error)
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*Response, error)
	IsFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	GetUserBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error)
	GetUserFollowed(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	GetUserFollower(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	GetFollowBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error)
}

type etcdclientClient struct {
	cc grpc.ClientConnInterface
}

func NewEtcdclientClient(cc grpc.ClientConnInterface) EtcdclientClient {
	return &etcdclientClient{cc}
}

func (c *etcdclientClient) Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) AddBlog(ctx context.Context, in *AddBlogRequest, opts ...grpc.CallOption) (*AddBlogResponse, error) {
	out := new(AddBlogResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/AddBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) ListBlog(ctx context.Context, in *ListBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error) {
	out := new(ListBlogResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/ListBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) GetBlog(ctx context.Context, in *GetBlogRequest, opts ...grpc.CallOption) (*GetBlogResponse, error) {
	out := new(GetBlogResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/GetBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/Follow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) IsFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/IsFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) GetUserBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error) {
	out := new(ListBlogResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/GetUserBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) GetUserFollowed(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/GetUserFollowed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) GetUserFollower(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/GetUserFollower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdclientClient) GetFollowBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error) {
	out := new(ListBlogResponse)
	err := c.cc.Invoke(ctx, "/etcdclientpb.Etcdclient/GetFollowBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EtcdclientServer is the server API for Etcdclient service.
// All implementations must embed UnimplementedEtcdclientServer
// for forward compatibility
type EtcdclientServer interface {
	Login(context.Context, *AuthRequest) (*AuthResponse, error)
	Register(context.Context, *AuthRequest) (*AuthResponse, error)
	AddBlog(context.Context, *AddBlogRequest) (*AddBlogResponse, error)
	ListBlog(context.Context, *ListBlogRequest) (*ListBlogResponse, error)
	GetBlog(context.Context, *GetBlogRequest) (*GetBlogResponse, error)
	Follow(context.Context, *FollowRequest) (*Response, error)
	IsFollow(context.Context, *FollowRequest) (*CheckResponse, error)
	GetUserBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error)
	GetUserFollowed(context.Context, *UserRequest) (*ListUserResponse, error)
	GetUserFollower(context.Context, *UserRequest) (*ListUserResponse, error)
	GetFollowBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error)
	mustEmbedUnimplementedEtcdclientServer()
}

// UnimplementedEtcdclientServer must be embedded to have forward compatible implementations.
type UnimplementedEtcdclientServer struct {
}

func (UnimplementedEtcdclientServer) Login(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedEtcdclientServer) Register(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedEtcdclientServer) AddBlog(context.Context, *AddBlogRequest) (*AddBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlog not implemented")
}
func (UnimplementedEtcdclientServer) ListBlog(context.Context, *ListBlogRequest) (*ListBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlog not implemented")
}
func (UnimplementedEtcdclientServer) GetBlog(context.Context, *GetBlogRequest) (*GetBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlog not implemented")
}
func (UnimplementedEtcdclientServer) Follow(context.Context, *FollowRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedEtcdclientServer) IsFollow(context.Context, *FollowRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFollow not implemented")
}
func (UnimplementedEtcdclientServer) GetUserBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBlog not implemented")
}
func (UnimplementedEtcdclientServer) GetUserFollowed(context.Context, *UserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollowed not implemented")
}
func (UnimplementedEtcdclientServer) GetUserFollower(context.Context, *UserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollower not implemented")
}
func (UnimplementedEtcdclientServer) GetFollowBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowBlog not implemented")
}
func (UnimplementedEtcdclientServer) mustEmbedUnimplementedEtcdclientServer() {}

// UnsafeEtcdclientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EtcdclientServer will
// result in compilation errors.
type UnsafeEtcdclientServer interface {
	mustEmbedUnimplementedEtcdclientServer()
}

func RegisterEtcdclientServer(s grpc.ServiceRegistrar, srv EtcdclientServer) {
	s.RegisterService(&Etcdclient_ServiceDesc, srv)
}

func _Etcdclient_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).Login(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).Register(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_AddBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).AddBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/AddBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).AddBlog(ctx, req.(*AddBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_ListBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).ListBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/ListBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).ListBlog(ctx, req.(*ListBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_GetBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).GetBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/GetBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).GetBlog(ctx, req.(*GetBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/Follow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_IsFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).IsFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/IsFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).IsFollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_GetUserBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).GetUserBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/GetUserBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).GetUserBlog(ctx, req.(*UserBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_GetUserFollowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).GetUserFollowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/GetUserFollowed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).GetUserFollowed(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_GetUserFollower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).GetUserFollower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/GetUserFollower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).GetUserFollower(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etcdclient_GetFollowBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdclientServer).GetFollowBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etcdclientpb.Etcdclient/GetFollowBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdclientServer).GetFollowBlog(ctx, req.(*UserBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Etcdclient_ServiceDesc is the grpc.ServiceDesc for Etcdclient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Etcdclient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "etcdclientpb.Etcdclient",
	HandlerType: (*EtcdclientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Etcdclient_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Etcdclient_Register_Handler,
		},
		{
			MethodName: "AddBlog",
			Handler:    _Etcdclient_AddBlog_Handler,
		},
		{
			MethodName: "ListBlog",
			Handler:    _Etcdclient_ListBlog_Handler,
		},
		{
			MethodName: "GetBlog",
			Handler:    _Etcdclient_GetBlog_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _Etcdclient_Follow_Handler,
		},
		{
			MethodName: "IsFollow",
			Handler:    _Etcdclient_IsFollow_Handler,
		},
		{
			MethodName: "GetUserBlog",
			Handler:    _Etcdclient_GetUserBlog_Handler,
		},
		{
			MethodName: "GetUserFollowed",
			Handler:    _Etcdclient_GetUserFollowed_Handler,
		},
		{
			MethodName: "GetUserFollower",
			Handler:    _Etcdclient_GetUserFollower_Handler,
		},
		{
			MethodName: "GetFollowBlog",
			Handler:    _Etcdclient_GetFollowBlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etcdclient/etcdclientpb/models.proto",
}
