// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package backendpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendClient interface {
	Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	AddBlog(ctx context.Context, in *AddBlogRequest, opts ...grpc.CallOption) (*AddBlogResponse, error)
	ListBlog(ctx context.Context, in *ListBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error)
	GetBlog(ctx context.Context, in *GetBlogRequest, opts ...grpc.CallOption) (*GetBlogResponse, error)
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*Response, error)
	IsFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	GetUserBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error)
	GetUserFollowed(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	GetUserFollower(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
	GetFollowBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error)
}

type backendClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendClient(cc grpc.ClientConnInterface) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) Login(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Register(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) AddBlog(ctx context.Context, in *AddBlogRequest, opts ...grpc.CallOption) (*AddBlogResponse, error) {
	out := new(AddBlogResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/AddBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) ListBlog(ctx context.Context, in *ListBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error) {
	out := new(ListBlogResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/ListBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetBlog(ctx context.Context, in *GetBlogRequest, opts ...grpc.CallOption) (*GetBlogResponse, error) {
	out := new(GetBlogResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/GetBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/Follow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) IsFollow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/IsFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetUserBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error) {
	out := new(ListBlogResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/GetUserBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetUserFollowed(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/GetUserFollowed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetUserFollower(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/GetUserFollower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) GetFollowBlog(ctx context.Context, in *UserBlogRequest, opts ...grpc.CallOption) (*ListBlogResponse, error) {
	out := new(ListBlogResponse)
	err := c.cc.Invoke(ctx, "/backendpb.Backend/GetFollowBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
// All implementations must embed UnimplementedBackendServer
// for forward compatibility
type BackendServer interface {
	Login(context.Context, *AuthRequest) (*AuthResponse, error)
	Register(context.Context, *AuthRequest) (*AuthResponse, error)
	AddBlog(context.Context, *AddBlogRequest) (*AddBlogResponse, error)
	ListBlog(context.Context, *ListBlogRequest) (*ListBlogResponse, error)
	GetBlog(context.Context, *GetBlogRequest) (*GetBlogResponse, error)
	Follow(context.Context, *FollowRequest) (*Response, error)
	IsFollow(context.Context, *FollowRequest) (*CheckResponse, error)
	GetUserBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error)
	GetUserFollowed(context.Context, *UserRequest) (*ListUserResponse, error)
	GetUserFollower(context.Context, *UserRequest) (*ListUserResponse, error)
	GetFollowBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error)
	mustEmbedUnimplementedBackendServer()
}

// UnimplementedBackendServer must be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (UnimplementedBackendServer) Login(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBackendServer) Register(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedBackendServer) AddBlog(context.Context, *AddBlogRequest) (*AddBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBlog not implemented")
}
func (UnimplementedBackendServer) ListBlog(context.Context, *ListBlogRequest) (*ListBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlog not implemented")
}
func (UnimplementedBackendServer) GetBlog(context.Context, *GetBlogRequest) (*GetBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlog not implemented")
}
func (UnimplementedBackendServer) Follow(context.Context, *FollowRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedBackendServer) IsFollow(context.Context, *FollowRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFollow not implemented")
}
func (UnimplementedBackendServer) GetUserBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBlog not implemented")
}
func (UnimplementedBackendServer) GetUserFollowed(context.Context, *UserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollowed not implemented")
}
func (UnimplementedBackendServer) GetUserFollower(context.Context, *UserRequest) (*ListUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollower not implemented")
}
func (UnimplementedBackendServer) GetFollowBlog(context.Context, *UserBlogRequest) (*ListBlogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowBlog not implemented")
}
func (UnimplementedBackendServer) mustEmbedUnimplementedBackendServer() {}

// UnsafeBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServer will
// result in compilation errors.
type UnsafeBackendServer interface {
	mustEmbedUnimplementedBackendServer()
}

func RegisterBackendServer(s grpc.ServiceRegistrar, srv BackendServer) {
	s.RegisterService(&Backend_ServiceDesc, srv)
}

func _Backend_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Login(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Register(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_AddBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).AddBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/AddBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).AddBlog(ctx, req.(*AddBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_ListBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).ListBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/ListBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).ListBlog(ctx, req.(*ListBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/GetBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetBlog(ctx, req.(*GetBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/Follow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_IsFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).IsFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/IsFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).IsFollow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetUserBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetUserBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/GetUserBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetUserBlog(ctx, req.(*UserBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetUserFollowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetUserFollowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/GetUserFollowed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetUserFollowed(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetUserFollower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetUserFollower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/GetUserFollower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetUserFollower(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_GetFollowBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).GetFollowBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendpb.Backend/GetFollowBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).GetFollowBlog(ctx, req.(*UserBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Backend_ServiceDesc is the grpc.ServiceDesc for Backend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Backend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backendpb.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Backend_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Backend_Register_Handler,
		},
		{
			MethodName: "AddBlog",
			Handler:    _Backend_AddBlog_Handler,
		},
		{
			MethodName: "ListBlog",
			Handler:    _Backend_ListBlog_Handler,
		},
		{
			MethodName: "GetBlog",
			Handler:    _Backend_GetBlog_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _Backend_Follow_Handler,
		},
		{
			MethodName: "IsFollow",
			Handler:    _Backend_IsFollow_Handler,
		},
		{
			MethodName: "GetUserBlog",
			Handler:    _Backend_GetUserBlog_Handler,
		},
		{
			MethodName: "GetUserFollowed",
			Handler:    _Backend_GetUserFollowed_Handler,
		},
		{
			MethodName: "GetUserFollower",
			Handler:    _Backend_GetUserFollower_Handler,
		},
		{
			MethodName: "GetFollowBlog",
			Handler:    _Backend_GetFollowBlog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/backendpb/models.proto",
}
